steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/dsg:$COMMIT_SHA",
        "--cache-from",
        "gcr.io/PROJECT_ID/dsg:latest",
        ".",
      ]
    timeout: 1200s
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/dsg:$COMMIT_SHA"]
    timeout: 1200s
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "dsg"
      - "--image"
      - "gcr.io/$PROJECT_ID/dsg:$COMMIT_SHA"
      - "--region"
      - "asia-northeast1"
      - "--platform"
      - "managed"
      - "--port"
      - "8080"
    timeout: 1200s
images:
  - "gcr.io/$PROJECT_ID/dsg:$COMMIT_SHA"
timeout: 2400s
